version: '3.8'

services:
  app:
    build:
      context: .
    volumes:
      - ./:/root/app
    container_name: dash
    ports:
      - "5050:5050"
    working_dir: '/root/app'
    environment:
      TZ: Asia/Tokyo